### DISCUSSION TITLE
New diesel features

### DISCUSSION THREAD

**Discussion by weiznich** [diesel-rs/diesel#3672] [Polls]
After the recent diesel 2.1 release I'm trying to gather some data about what features are considered to be missing by our users. If you have suggestions for different features please leave a comment below.

If you want to support the work on a certain feature via contributions or sponsoring please reach out.

**Comment by ethever** [comment]
Hey, if `cursor-based` pagination available out of box, it would great help to using sqlite in my production. https://github.com/SeaQL/sea-orm/blob/master/src/executor/cursor.rs

**Comment by Ten0** [comment]
Full featured sub-query aliasing:
```sql
SELECT users.id, users.username, SUM(p.nb_views) FROM users
INNER JOIN (
    SELECT
        posts.user_id,
        (SELECT COUNT(*) FROM views WHERE views.post_id = posts.id) as nb_views
    FROM posts
) as p ON p.user_id = users.id
GROUP BY users.id
```

(I'm aware this particular query can be written differently, that's just for the example.)

Notably this would (should) enable batch updates:
```sql
UPDATE posts SET content = vals.content
FROM (VALUES (1, "Hello"), (2, "World")) as vals(post_id, content) WHERE vals.post_id = posts.id
```

**Comment by Ten0** [comment]
Compile-time check that fields that are not `Nullable` and don't have a default value are properly set when using `insert_into`.
NB: Not sure how this interacts with `BEFORE INSERT` triggers. Maybe there should be an opt-in/out.

**Comment by forest1102** [comment]
Your project helps a lot.  
One feature I want is splitting into multiple schema.rs. 
For instance, making the following diesel.toml

```toml
[[print_schema]]
file = "db_company/src/schema.rs"
filter = { only_tables = ["^companies$"] }
[[print_schema]]
file = "db_user/src/schema.rs"
filter = { only_tables = ["^users$"] }
```

Then, the `companies` schema info is written in `db_company/src/schema.rs`, while the `users` schema info goes to `db_user/src/schema.rs`. 

## Motivation

- Readability
  - By splitting schema.rs, we can easily search definition of tables. 
- Build Performance
  - This feature will parallelize building schema.rs. which will result in better build performance. 

## Current Behavior

print_schema field only allows only on schema info.  
So, what I do right now is select one print_schema and comment out others like the following files. 

```toml
[print_schema]
file = "db_company/src/schema.rs"
filter = { only_tables = ["^companies$"] }
# [print_schema]
# file = "db_user/src/schema.rs"
# filter = { only_tables = ["^users$"] }
```
