### DISCUSSION TITLE
connecting to postgres container

### DISCUSSION THREAD

**Discussion by brahimABD98** [diesel-rs/diesel#4059] [Q&A]
I have this super simple docker compose service
```yml  
db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: server
    volumes:
      - db-data:/var/lib/postgresql/data
 ```
when I run (tried both 127.0.0.1. and localhost)
```sh
diesel setup --database-url postgres://postgres:postgres@127.0.0.1:5432/server
```
I keep getting the same error message
```sh
Creating database: server
Could not connect to database via `postgres://postgres:postgres@127.0.0.1/postgres`: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "postgres"
```
db log show this too
```sh
password authentication failed for user "postgres"
```
