### DISCUSSION TITLE
diesel setup try to connect wrong db

### DISCUSSION THREAD

**Discussion by ammoti** [diesel-rs/diesel#4136] [Q&A] [answered]
Hello everyone,
This is a little bit weird, on my windows machine I try to run "diesel setup" command and output is looking like;
`Creating database: hale
Could not connect to database via postgres://username:password@127.0.0.1/postgres: connection to server at "127.0.0.1", port 5432 failed: FATAL:  password authentication failed for user "username"`
but in my .env file is looking like;
`DATABASE_URL=postgres://test:test123@127.0.0.1/hale`
`POSTGRES_DB=hale`
`POSTGRES_USER=test`
`POSTGRES_PASSWORD=test123`

My db name is hale but DATABASE_URL try to connect to **postgres**  I  don't know may be my configuration is wrong I could not find any related issue, what's wrong with me? 
I tried to change host, port etc. and I always show correct DATABASE_URL except the DB_NAME

My postgresql is running on Docker and I tried prune volume and rest of all thing and here is my compose yml;
```
`version: '3.8'
services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
      interval: "10s"
      timeout: "5s"
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:`
```
in my macbook its working like a charm but in windows machine I could not.
