### DISCUSSION TITLE
Use the PosgreSQL backend without TLS support

### DISCUSSION THREAD

**Discussion by kleinesfilmroellchen** [diesel-rs/diesel#4445] [Show and tell]
I’m documenting this since I couldn’t find it anywhere in the official documentation, not even under the various feature flags and backend documentations.

In many cases, such as a connection to a local database, via Unix socket, via VPN, or via other private tunnel, TLS support is not required for connecting to a PostgreSQL database. Furthermore, for development, setting up certificates is unnecessary if you’re only dealing with test data in your application anyways.

Therefore, TLS support can be turned off for the PostgreSQL backend. Since libpq has no support for RusTLS, only OpenSSL, this can arguably be considered a security improvement given the spotty history of OpenSSL. Debatable arguments aside, this reduces your dependency count and reliance on system-specific libraries that are not available (or require extra steps) on certain platforms. Even with a web server framework, I was able to set up my dependencies entirely without either RusTLS or OpenSSL.

Finally, here’s what to do in your Cargo.toml:

```toml
[dependencies]
# whatever version you need...
diesel = { version = "2", features = ["postgres"] }
pq-sys = { version = "0.6", features = ["bundled_without_openssl"] }
```

The separate specification of pq-sys, even though you’re never using it in your project directly, will be picked up by diesel. This also configures pq-sys with the bundled libpq compiled from source, which is by far the most convenient way to use the PostgreSQL backend on Windows.

You can verify with `cargo tree` that no `openssl-sys` is found in your dependency tree.

Enjoy :)
