### DISCUSSION TITLE
the trait `diesel::Expression` is not implemented for `BigDecimal on diesel 2.0

### DISCUSSION THREAD

**Discussion by SpringChiu** [diesel-rs/diesel#4645] [Q&A]
### Versions

- **Rust:**
rustc 1.86.0
- **Diesel:**
diesel = { version = "2", features = ["uuid", "postgres", "numeric", "serde_json"] }
- **Database:**
postgres PostgreSQL 15.2
- **Operating System**
mac m3
### Feature Flags

here are my all dependecies:
```toml
actix-web = { workspace = true }
diesel = { version = "2", features = ["uuid", "postgres", "numeric", "serde_json"] }
diesel-async = { version = "0.5", features = ["postgres", "bb8", "async-connection-wrapper"] }
dotenvy = { workspace = true }
env_logger = { workspace = true }
log = { workspace = true }
uuid = { workspace = true }
bigdecimal = { version = "0.4.8", features = ["serde", "serde_json"] }
serde_json = "1.0.108"
serde = "1.0.192"
```

- **diesel:**
features = ["uuid", "postgres", "numeric", "serde_json"]
### What are you trying to accomplish?
I want to add a numberic type `fee                  numeric  not null` for the table:
```sql
CREATE TABLE IF NOT EXISTS items
(
    id uuid DEFAULT gen_random_uuid() PRIMARY KEY,
    name VARCHAR NOT NULL,
    fee                  numeric  not null
);
```
after than I run migration: `diesel migration run`
and it generated schema:
```rust
diesel::table! {
    items (id) {
        id -> Uuid,
        name -> Varchar,
        fee -> Numeric,
    }
}
```
and then I want to build it with model:
```rust
use super::schema::items;

/// Item details.
#[derive(Debug, Clone, Serialize, Deserialize, Queryable, Selectable, Insertable)]
#[diesel(table_name = items)]
pub struct Item {
    pub id: Uuid,
    pub name: String,
    pub fee: BigDecimal,
}
```

but it build failed
### What is the expected output?
it should be success

### What is the actual output?
it build failed error:
```
error[E0277]: the trait bound `BigDecimal: diesel::Expression` is not satisfied
  --> databases/diesel-async/src/models.rs:14:9
   |
14 |     pub fee: BigDecimal,
   |         ^^^ the trait `diesel::Expression` is not implemented for `BigDecimal`
   |
   = help: the following other types implement trait `diesel::Expression`:
             &T
             (T0, T1)
             (T0, T1, T2)
             (T0, T1, T2, T3)
             (T0, T1, T2, T3, T4)
             (T0, T1, T2, T3, T4, T5)
             (T0, T1, T2, T3, T4, T5, T6)
             (T0, T1, T2, T3, T4, T5, T6, T7)
           and 135 others
   = note: required for `BigDecimal` to implement `AsExpression<diesel::sql_types::Numeric>`

error[E0277]: the trait bound `BigDecimal: diesel::Expression` is not satisfied
```
