### ISSUE TITLE
Website styling: Text readability

### ISSUE THREAD

**Issue by theduke** [diesel-rs/diesel#1052]
The white text on the light blue background is quite hard to read, especially since the text is so free floating on the page.

I've played around a bit and I'd suggest giving the content area a bit of a padding and a backgroudn color.

something like:

```css
.guide-wrapper {
    margin-right: 0;
    padding: 20px 30px;
    background: #3e4d66;
    border-radius: 10px;
}
```

This would also require makign .guide-wrapper a bit larger in the @media css.

```css
@media screen and (min-width: 53.75em) {
  .guide-wrapper {
      width: 70%
  }
  
}
...
```
