### ISSUE TITLE
Compiler cannot find `diesel::insert_into` for version from Rust package registry.

### ISSUE THREAD

**Issue by anlaakso** [diesel-rs/diesel#1261]
### Versions

- **Rust:1.22.0-nightly**
- **Diesel:0.16.0**
- **Database:Postgres**
- **Operating System: macOS Sierra**

### Feature Flags

- **diesel:postgres**
- **diesel_codegen:postgres**

## Problem Description
I have experienced a very specific issue around 'diesel::insert_into' function.
If I run build with dependencies described below

```toml
[dependencies]
diesel = { version = "0.16.0", features = ["postgres"] }
diesel_codegen = { version = "0.16.0", features = ["postgres"] }
dotenv = "0.9.0"

```
the compiler says 

```text
error[E0425]: cannot find function `insert_into` in module `diesel`
  --> src/main.rs:31:31
   |
31 |     let rows: usize = diesel::insert_into(example)
   |                               ^^^^^^^^^^^ not found in `diesel`
```

But if I get diesel directly from GitHub, it works well. 
```toml
[dependencies]
diesel = { git="https://github.com/diesel-rs/diesel.git", features = ["postgres"] }
diesel_codegen = { version = "0.16.0", features = ["postgres"] }
dotenv = "0.9.0"
```
