### ISSUE TITLE
Following `diesel` sqlite example fails with 1.0.0-beta1

### ISSUE THREAD

**Issue by bitemyapp** [diesel-rs/diesel#1392]
```
   Compiling diesel v1.0.0-beta1 (https://github.com/diesel-rs/diesel?rev=821c840d0c8dccd37ee5f3554304d16c7064ea0a#821c840d)
   Compiling diesel v1.0.0-beta1
   Compiling native-tls v0.1.4
   Compiling tokio-tls v0.1.3
   Compiling hyper-tls v0.1.2
   Compiling egg-mode v0.11.0
   Compiling infer_schema_internals v1.0.0-beta1
   Compiling infer_schema_macros v1.0.0-beta1
   Compiling diesel_infer_schema v1.0.0-beta1 (https://github.com/diesel-rs/diesel?rev=821c840d0c8dccd37ee5f3554304d16c7064ea0a#821c840d)
   Compiling twook v0.1.0 (file:///home/callen/work/twook)
error: unexpected end of macro invocation
  --> src/main.rs:18:5
   |
18 |     infer_schema!("dotenv:DATABASE_URL");
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: this error originates in a macro outside of the current crate

error: aborting due to previous error

error: Could not compile `twook`.

To learn more, run the command again with --verbose.
Makefile:9: recipe for target 'build' failed
make: *** [build] Error 101
```

Expanded macro invocation error

```
 -Z external-macro-backtrace`
error: unexpected end of macro invocation
 --> <infer_schema macros>:3:14
  |
1 | | ( $ database_url : expr ) => {
  | |____________________________________^
2 |   mod __diesel_infer_schema {
3 |   # [ derive ( InferSchema ) ] # [
  |  ______________^
src/main.rs:18:5: 18:42 note: in this expansion of infer_schema! (defined in <infer_schema macros>)
<infer_schema macros>:3:14: 3:25 note: in this expansion of #[derive(InferSchema)]

error: aborting due to previous error
```

The following should be a minimal repro from my `main.rs`:

```rust
#[macro_use]
pub extern crate diesel;
#[macro_use]
extern crate diesel_infer_schema;
#[macro_use]
extern crate dotenv;

mod common;

use common::tokio_core::reactor;
use egg_mode::tweet::Tweet;
use diesel::prelude::*;
use dotenv::dotenv;
use std::env;

infer_schema!("dotenv:DATABASE_URL");
```

```toml
[package]
name = "twook"
version = "0.1.0"

[dependencies]
chrono = "0.4.0"
egg-mode = "0.11.0"
diesel = { git = "https://github.com/diesel-rs/diesel", rev = "821c840d0c8dccd37ee5f3554304d16c7064ea0a", features = ["sqlite"] }
diesel_infer_schema = { git = "https://github.com/diesel-rs/diesel", rev = "821c840d0c8dccd37ee5f3554304d16c7064ea0a", features = ["sqlite"] }
dotenv = "0.9.0"
futures = "*"
tokio-core = "0.1.10"
```
