### ISSUE TITLE
the trait `diesel::connection::Connection` is not implemented for `diesel::PgConnection`

### ISSUE THREAD

**Issue by chillcaw** [diesel-rs/diesel#1441]
My code is as follows:
```rust
extern crate diesel;
extern crate diesel_codegen;
extern crate dotenv;
extern crate r2d2;
extern crate r2d2_diesel;

use diesel::pg::PgConnection;
use r2d2::Pool;
use r2d2_diesel::ConnectionManager;
use dotenv::dotenv;
use std::env;

pub fn connect_db() -> Pool<ConnectionManager<PgConnection>> {
    dotenv().ok();

    let database_url = env::var("DATABASE_URL")
        .expect("DATABASE_URL must be set");
    let manager = ConnectionManager::<PgConnection>::new(database_url);
    Pool::new(manager).expect("Failed to create pool.");
}
```

I don't understand why the error is even saying `diesel::PgConnection`, since I'm using `diesel::pg::PgConnection`.

**Comment by Eijebong** [comment]
You probably have multiple versions of diesel in your dependencies. Check that you're using the right version for r2d2 (it should be the same as the diesel one) and run cargo update.

**Comment by chillcaw** [comment]
Cargo.toml:

```toml
diesel = { version = "1.0.0-rc1", features = ["postgres"] }
dotenv = "0.9.0"
diesel_codegen = { version = "0.16.0", features = ["postgres"] }
r2d2-diesel = "1.0.0-rc1"
r2d2 = "0.8.2"
```

**Comment by Eijebong** [comment]
You shouldn't have `diesel_codegen` as it was removed in 0.99, see the changelog https://github.com/diesel-rs/diesel/blob/master/CHANGELOG.md

**Comment by chillcaw** [comment]
Ah cool, I will have to look through diesels docs, I have been going by rocket's docs. They must be slightly out of date.

new Cargo.toml for people with the same problem:
```toml
diesel = { version = "1.0.0-rc1", features = ["postgres"] }
dotenv = "0.9.0"
r2d2-diesel = "1.0.0-rc1"
r2d2 = "0.8.2"
```
