### ISSUE TITLE
Expose multi-db connection inference from diesel-cli

### ISSUE THREAD

**Issue by igalic** [diesel-rs/diesel#1853]
## Setup

in Plume and Rustodon we want to support PostgreSQL and SQLite for smaller or dev/test setups.
Both projects are currently working on patches adding SQLite support: https://github.com/Plume-org/Plume/pull/226 https://github.com/rustodon/rustodon/pull/12

### Versions

- **Rust:** nightly
- **Diesel:** 1.3.×
- **Database:** postgres & sqlite
- **Operating System**

### Feature Flags

```toml
[dependencies.diesel_cli]
features = ["postgres", "sqlite"]
version = "1.3.1"

[dependencies.diesel]
features = ["postgres", "sqlite", "r2d2", "chrono"]
version = "*"
```

## Problem Description

our problem is that we have to reimplement a lot of diesel-cli functionality for the setup and the normal operation of the program if you want to support more than one database.

currently, this seems to be in

https://github.com/diesel-rs/diesel/blob/db9ffe2eea6b15235751055dc3e46d63072093e2/diesel_cli/src/database.rs#L75-L86

but i'm not sure how to acces or if that's possible at all

### What are you trying to accomplish?

We would like to easily use both databases transparently

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.

this might be related to https://github.com/diesel-rs/diesel/issues/357
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
