### ISSUE TITLE
One test fails when I run `bin/test` locally

### ISSUE THREAD

**Issue by DNNX** [diesel-rs/diesel#2133]
### Versions

- **Rust:** `rustc 1.31.0 (abe02cefd 2018-12-04)`
- **Diesel:** v1.4.2 and 0b6c59e36cef3faea0184404e43e3db4739d1193 (latest master at the time of writing)
- **Database:** `mysql  Ver 8.0.17 for osx10.13 on x86_64 (Homebrew)` - client libraries, `8.0.17` - server.
- **Operating System** docker host is `macOS High Sierra 10.13.6 (17G65)`, not sure what OS mysql container runs on.

### Feature Flags

- **diesel:** `mysql`

## Problem Description

When I run `bin/test`, all the tests pass except one. 

### What are you trying to accomplish?

I want to have all tests green on my machine in order to be able to play with diesel source code and possibly contribute.

### What is the expected output?

All tests are green.

### What is the actual output?

```
$ cd diesel && RUST_TEST_THREADS=1 cargo test --no-default-features --features mysql

...

---- src/query_dsl/mod.rs - query_dsl::QueryDsl::inner_join (line 398) stdout ----
thread 'src/query_dsl/mod.rs - query_dsl::QueryDsl::inner_join (line 398)' panicked at 'test executable failed:

thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Ok([("Sean", "Sean\'s post"), ("Sean", "Sean is a jerk")])`,
 right: `Err(DatabaseError(__Unknown, "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'|| ?)\' at line 1"))`', src/query_dsl/mod.rs:30:1
note: Run with `RUST_BACKTRACE=1` for a backtrace.

', librustdoc/test.rs:367:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    src/query_dsl/mod.rs - query_dsl::QueryDsl::inner_join (line 398)

test result: FAILED. 116 passed; 1 failed; 16 ignored; 0 measured; 0 filtered out
```

I tried it on the latest master and on `v1.4.2`. Same error.

### Are you seeing any additional errors?

Nope.

### Steps to reproduce

I followed the [contributing guidelines](https://github.com/diesel-rs/diesel/blob/master/CONTRIBUTING.md) when setting up everything locally. Here is what I did, precisely:

* Clone the repo and `cd` into it
* `cp .env.sample .env`, also bump all ports by 1, i.e. 5432 -> 5433 and 3306 -> 3307.
* Made the same changes in `docker-compose.yml`, so that ports from docker don't conflict with my local database servers.
* `brew install mysql`
* `bin/test`

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel.

**Comment by weiznich** [comment]
It seems like this issue is specific to mysql 8.0.17. We are already aware of this but nobody had enough time to look into it yet. Maybe I will find some time in the next few days. In the mean time just use 8.0.16 which should work fine.

See #2108 for some details.

**Comment by DNNX** [comment]
Yep, it worked. The following diff fixes the problem:

```diff
diff --git a/docker-compose.yml b/docker-compose.yml
index 80bd7b1a..9592e55a 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,7 +1,7 @@
 version: '3'
 services:
   mysql:
-    image: mysql
+    image: mysql:8.0.16
     container_name: diesel.mysql
     volumes:
       - "mysql-data:/var/lib/mysql/:delegated"
```

I also had to delete old docker volume with `docker volume rm diesel_mysql-data` because otherwise mysql wouldn't start.

Thank you for the prompt response and feel free to close this issue if it's a duplicate.

**Comment by DNNX** [comment]
Looking at the error message and MySQL changelog, this seems relevant:

https://dev.mysql.com/doc/relnotes/mysql/8.0/en/news-8-0-17.html#mysqld-8-0-17-deprecation-removal

> Use of || is deprecated unless the PIPES_AS_CONCAT SQL mode is enabled. In that case, || signifies the SQL-standard string concatenation operator).

Although we do set `PIPES_AS_CONCAT` there: https://github.com/diesel-rs/diesel/blob/0b6c59e36cef3faea0184404e43e3db4739d1193/diesel/src/mysql/connection/mod.rs#L134... So it should still work.

**Comment by JohnTitor** [comment]
Thanks for your report, I'll take a look shortly.

**Comment by DNNX** [comment]
I updated docker-compose to run the two versions of mysql side by side on different ports, and created a small isolated script to show the difference between them. Mysql client needs to be installed locally in order to run them.

``` bash
# Note: the two commands are only different by port number.
$ echo "SET sql_mode=(SELECT CONCAT(@@sql_mode, ',PIPES_AS_CONCAT')); select 'ab' like 'a' || '%'" | mysql --port 3307 --host localhost --protocol=TCP --user root diesel_test
'ab' like 'a' || '%'
1

$ echo "SET sql_mode=(SELECT CONCAT(@@sql_mode, ',PIPES_AS_CONCAT')); select 'ab' like 'a' || '%'" | mysql --port 3308 --host localhost --protocol=TCP --user root diesel_test
ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '|| '%'' at line 1
```

My docker-compose:

```yml
version: '3'
services:
  mysql:
    image: mysql:8.0.17
    container_name: diesel.mysql
    volumes:
      - "mysql-data:/var/lib/mysql/:delegated"
      - "./docker/mysql/init:/docker-entrypoint-initdb.d"
    ports:
      - "3308:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

  mysql-old:
    image: mysql:8.0.16
    container_name: diesel.mysql.old
    volumes:
      - "mysql-data-old:/var/lib/mysql/:delegated"
      - "./docker/mysql/init:/docker-entrypoint-initdb.d"
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true

volumes:
  mysql-data:
    driver: local
  mysql-data-old:
    driver: local
```
