### ISSUE TITLE
How to execute law sql that “Create TABLE IF NOT EXIST posts ….”  on android os.

### ISSUE THREAD

**Issue by Guang1234567** [diesel-rs/diesel#2224]
Hello dev:

As you known according the issue title,  i just confuse how to executing raw sql to create table by diesel  for android platform?

Is it support? Could you give me some suggestion? Thanks.

-----

I find some solution for upgrade or downgrade the sqlite database :

https://docs.rs/diesel_migrations/1.4.0/diesel_migrations/macro.embed_migrations.html

**Comment by Guang1234567** [comment]
@other_mobile_dev:

My solution for migrating the sqlite on mobile platform (android):

1.  add `diesel_migrations`

`Cargo.toml`
```toml
[target.'cfg(target_os="android")'.dependencies]
jni = { version = "0.14.0", default-features = false }
android_log = "0.1.3"
rusqlite = {version = "0.20.0", features = ["bundled"]}
diesel = { version = "1.4.3", features = ["sqlite"] }
diesel_migrations = “1.4.0”
```

2.   create `create_posts` migration

```bash
diesel migration generate create_posts
```

3. migrate sqlite db at runtime.

https://docs.rs/diesel_migrations/1.4.0/diesel_migrations/macro.embed_migrations.html

```rust
embed_migrations!("./migrations");

fn main() {
    let connection = establish_connection();

    // This will run the necessary migrations.
    embedded_migrations::run(&connection);

    // By default the output is thrown out. If you want to redirect it to stdout, you
    // should call embedded_migrations::run_with_output.
    embedded_migrations::run_with_output(&connection, &mut std::io::stdout());
}
```

4.  create `create_users` migration  to upgrade sqlite db.

```bash
diesel migration generate create_users
```

5. compile your `librust.so` again, but remember that “[This macro (`embed_migrations`) will read your migrations at compile time, and embed a module you can use to execute them at runtime without the migration files being present on the file system.](https://docs.rs/diesel_migrations/1.4.0/diesel_migrations/macro.embed_migrations.html)”.

Because the compiler not smart !
It can not detect the change caused by `diesel migration generate create_users` !
So you must run `cargo clean` to force this macro (`embed_migrations`) read your newer migration again!
