### ISSUE TITLE
Feature request: sqlcipher support 

### ISSUE THREAD

**Issue by silvioprog** [diesel-rs/diesel#2284]
Hi.

It would be nice to support [sqlcipher](https://github.com/jgallagher/rusqlite/blob/master/Cargo.toml#L41) out of the box, something like:

```toml
[dependencies]
diesel = { version = "1.5", features = ["sqlite", "sqlcipher"] }
```
... allowing the users to crypt their SQLite data bases for safety.

Thank you!
