### ISSUE TITLE
the trait bound uuid::Uuid: diesel::Expression is not satisfied

### ISSUE THREAD

**Issue by frederikhors** [diesel-rs/diesel#2348]
### Versions

- **Rust:** 1.42.0
- **Diesel:** 1.4.4
- **Database:** Postgres 12
- **Operating System:** Win 10

### Cargo.toml
```
diesel = { version = "=1.4.4", features = ["postgres", "r2d2", "uuid", "chrono"] }
diesel_migrations = "=1.4.0"
...
uuid = { version = "=0.8.1", features = ["serde", "v4"] }
```

### What are you trying to accomplish?

Use `uuid` with `diesel` with no problems.

### What is the expected output?

It works.

### What is the actual output?

`the trait bound uuid::Uuid: diesel::Expression is not satisfied`

### Are you seeing any additional errors?

Nope.

I saw:

- https://github.com/uuid-rs/uuid/issues/453 and
- https://github.com/diesel-rs/diesel/pull/2235

But still problems, **why?**

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)

**Comment by weiznich** [comment]
Basically a duplicate of https://github.com/diesel-rs/diesel/issues/1900.

(You need to use the `uuidv07` feature to make this work.)

**Comment by frederikhors** [comment]
@weiznich thank for your answer.

Now I'm using:

```toml
[dependencies]
actix-web = "=2.0.0"
actix-rt = "=1.0.0"
chrono = { version = "=0.4.11", features = ["serde"] }
diesel = { version = "=1.4.4", features = ["postgres", "r2d2", "uuidv07", "chrono"] }
diesel_migrations = "=1.4.0"
dotenv = "=0.15.0"
env_logger = "=0.7.1"
lazy_static = "=1.4.0"
log = "=0.4.8"
r2d2 = "=0.8.8"
serde = "=1.0.105"
serde_json = "=1.0.50"
uuid = { version = "=0.8.1", features = ["serde", "v4"] }
```

But Cargo gives me a warning:

`warning: Feature uuidv07 of package diesel has been obsolete in version 1.4.4`

**Comment by weiznich** [comment]
We do not say that anywhere in our code, so I'm not sure where cargo is getting this information from. You should probably rise a issue there.

**Comment by frederikhors** [comment]
`there` where?

**Comment by weiznich** [comment]
In the issue tracker of whichever tool is giving you this warning. So if it's cargo itself then here: https://github.com/rust-lang/cargo/, if it's some custom subcommand in then in their issue tracker.

**Comment by problame** [comment]
FWIW, I am using diesel 1.4.5 with uuid 0.8.1  and adding the `uuidv07` feature just fixed the problem for me. Is there a cfg! in diesel 1.4.5 that still uses `uuidv07` ?

**Comment by gaku-sei** [comment]
Second @problame's issue, the following dependencies and features doesn't work:

```toml
diesel = {version = "1.4.4", features = ["chrono", "postgres", "r2d2", "uuid"]}
uuid = "0.8.2"
```

But this does:

```toml
diesel = {version = "1.4.4", features = ["chrono", "postgres", "r2d2", "uuidv07"]}
uuid = "0.8.2"
```
