### ISSUE TITLE
Can't find Json sql_type with 1.4.5 tag in MySQL feature.

### ISSUE THREAD

**Issue by Arcovv** [diesel-rs/diesel#2439]
### Versions

- **Rust:** 1.46.0-nightly
- **Diesel:** 1.4.5
- **Database:** MySQL
- **Operating System** MacOS

### Feature Flags

- **diesel:** ["chrono", "mysql", "r2d2", "numeric", "serde_json"]

## Problem Description

```toml
[dependencies.diesel]
version = "1.4.5"
default-features = false
features = ["chrono", "mysql", "r2d2", "numeric", "serde_json"]
```

I'm using MySql json type to save data. After `diesel print-schema`, compile will error me that "cannot find type `Json` in this scope".

I found that `sql_types::Json` is only defined in master branch.
https://github.com/diesel-rs/diesel/blob/b4c57c2247875cab34967de792531590abadb7db/diesel/src/sql_types/mod.rs#L364

And I could not find that in 1.4.5 version.

### My Workaround

I use master branch in my cargo.toml file now. But I think it is not an ideal solution.

```toml
[dependencies.diesel]
git = "https://github.com/diesel-rs/diesel"
package = "diesel"
rev = "b4c57c2247875cab34967de792531590abadb7db"
features = ["chrono", "mysql", "r2d2", "numeric", "serde_json"]
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) for similar issues.
- [ ] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
