### ISSUE TITLE
diesel::expression_methods::TextOrNullableText seems to be missing for diesel::sql_types::Uuid

### ISSUE THREAD

**Issue by Roms1383** [diesel-rs/diesel#2693]
Hello, thanks for this wonderful library !

I ran this morning into an issue when trying to use `like` on table fields of type `diesel::sql_types::Uuid`.

### Versions

- **Rust:** rustc 1.51.0 (2fd73fabe 2021-03-23)
- **Diesel:** 1.4.6
- **Database:** psql (PostgreSQL) 13.2
- **Operating System**
<img width="209" alt="Screen Shot 2564-03-30 at 11 36 58" src="https://user-images.githubusercontent.com/21016014/112934567-44a2e400-914c-11eb-9225-cb401a7d743a.png">

### Feature Flags

- **diesel:** ["postgres", "chrono", "r2d2", "uuidv07", "numeric"]

## Problem Description

When trying to use `like` or `ilike` (for Postgres) with a diesel table field of type `Uuid`, I run into the missing implementation of `diesel::expression_methods::TextOrNullableText` for `diesel::sql_types::Uuid`.

### What are you trying to accomplish?

Just using `LIKE` filter on a query.

### What is the expected output?

It should be able to filter `diesel::sql_types::Uuid` with `LIKE`.

### What is the actual output?

<img width="377" alt="Screen Shot 2564-03-30 at 11 34 06" src="https://user-images.githubusercontent.com/21016014/112934426-f261c300-914b-11eb-90d3-a8c85a8a4896.png">
Compilation error as shown above.

### Are you seeing any additional errors?

None.

### Steps to reproduce

```toml
# Cargo.toml
[dependencies]
diesel = { version = "1.4.5", features = ["postgres", "chrono", "r2d2", "uuidv07", "numeric"] }
uuid = { version = "0.8", features = ["serde", "v4"] }
```

```rust
// schema.rs
table! {
    use diesel::sql_types::*;
    my_table (id) {
        id -> Uuid,
    }
}
```

```rust
// querying like :
let mut query = my_table::table.into_boxed::<diesel::pg::Pg>();
query = query.filter(my_table::id.ilike("78621%"));
// or : query = query.filter(my_table::id.like("78621%"));
let results = query.load(&connection)?;
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)
- [ ] I have already looked at the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
- [x] This issue can be reproduced on Rust's stable channel : stable-aarch64-apple-darwin (default)
- [ ] This issue can be reproduced without requiring a third party crate : requires at least [uuid](https://crates.io/crates/uuid)

Thanks :)

**Comment by Mingun** [comment]
```toml
diesel = { ... features = [..., "uuidv07", ...] }
uuid = { version = "0.8", ... }
```
Hm...

**Comment by Roms1383** [comment]
Yes @Mingun that's what I have already (please check the `Cargo.toml` excerpt).

**Comment by Roms1383** [comment]
@Mingun or do you mean remove the `uuid` dependency ?

**Comment by Mingun** [comment]
I mean that you probable need to use "uuid" feature of the `diesel` crate or use `uuid` with version <=0.7.

There are several closed issues in this repo with similar "trait not implemented" errors that connected with incompatible versions of dependencies

**Comment by Roms1383** [comment]
well if I switch to :
```toml
[dependencies]
diesel = { version = "1.4.5", features = ["postgres", "chrono", "r2d2", "uuidv07", "numeric"] } # <-- using uuid feature as before
uuid = { version = "0.6", features = ["serde", "v4"] } # <-- with 0.6 version here
```

The problem is then I end up with compilation errors like :
<img width="911" alt="Screen Shot 2564-03-30 at 14 10 37" src="https://user-images.githubusercontent.com/21016014/112948214-fe587f80-9161-11eb-9e44-35369fcc3243.png">
And :
<img width="1217" alt="Screen Shot 2564-03-30 at 14 13 20" src="https://user-images.githubusercontent.com/21016014/112948385-36f85900-9162-11eb-905d-ac1bc0d18414.png">

I have also tried in that different setup :
```toml
diesel = { version = "1.4.6", features = ["postgres", "chrono", "r2d2", "uuid", "numeric"] }
uuid = { version = "0.8.2", features = ["serde", "v4"] }
```
By switching `uuid`'s `to_hyphenated()` method to `hyphenated()` but then running into these compilation errors :
<img width="1014" alt="Screen Shot 2564-03-30 at 14 24 55" src="https://user-images.githubusercontent.com/21016014/112949736-be929780-9163-11eb-8939-7156d28cd125.png">

Or even :
```toml
diesel = { version = "1.4.6", features = ["postgres", "chrono", "r2d2", "uuid", "numeric"] }
uuid = { version = "0.6.5", features = ["serde", "v4"] }
```
But no matter which I'm still running into these compilation errors :
<img width="1323" alt="Screen Shot 2564-03-30 at 14 22 58" src="https://user-images.githubusercontent.com/21016014/112949494-7a9f9280-9163-11eb-80bb-d329c8787e32.png">

So I must admit that I'm a little bit confused here @Mingun.
