### ISSUE TITLE
Compile errors with feature resolver ver 2 and diesel_migrations

### ISSUE THREAD

**Issue by reisnera** [diesel-rs/diesel#2783]
### Versions

- **Rust: 1.52.1**
- **Diesel: 1.4.6**
- **diesel_migrations: 1.4.0**
- **Database: sqlite**
- **Operating System: Ubuntu in WSL2**

### Feature Flags

- **diesel: ["sqlite"]**
- **diesel_migrations: ["sqlite"]**

### What are you trying to accomplish?

Building an empty project with diesel and diesel_migrations.

### What is the expected output?

An error-free build.

### What is the actual output?

Multiple (aborted after 12 errors) essentially identical errors (though different line numbers) of the form:

```shell
error[E0433]: failed to resolve: could not find `sqlite` in `diesel`
  --> /home/alex/.cargo/registry/src/github.com-1ecc6299db9ec823/diesel-1.4.6/src/sql_types/mod.rs:37:48
   |
37 | #[derive(Debug, Clone, Copy, Default, QueryId, SqlType)]
   |                                                ^^^^^^^ could not find `sqlite` in `diesel`
   |
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

### Are you seeing any additional errors?

No

### Steps to reproduce

1. Create a new empty project: ```cargo new failstocompile```
2. Update Cargo.toml to the following (**note the use of the new feature resolver**)
```toml
[package]
name = "failstocompile"
version = "0.1.0"
edition = "2018"
resolver = "2"

[dependencies]
diesel = { version = "1.4.6", features = ["sqlite"] }
diesel_migrations = { version = "1.4.0", features = ["sqlite"] }
```
3. ```cargo build```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate
