### ISSUE TITLE
[r2d2] Scheduled thread pool instant::wasm::Instant type error + WASM compilation with Wrangler (Cloudflare Workers)

### ISSUE THREAD

**Issue by hariria** [diesel-rs/diesel#2927]
## Setup

```toml
[package]
version = "0.1.0"
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
cfg-if = "0.1.2"
diesel = { version = "1.4.4", features = ["postgres", "r2d2"] }
dotenv = "0.15.0"
worker = "0.0.6"
serde_json = "1.0.67"

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.1", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
wee_alloc = { version = "0.4.2", optional = true }

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[package.metadata.wasm-pack.profile.release]
wasm-opt = false

```

### Versions

- **Rust: rustc 1.55.0**
- **Diesel: 1.4.4**
- **Postgres: Not relevant**
- **Macbook M1 chip, running Big Sur**

## Problem Description

When I add `r2d2` as a feature for my `diesel` dependency in my cargo.toml, it's unable to compile my code to a wasm output. The error states that the `instant::wasm::Instant` struct was expected, but the `Instant` struct was found.

Cloudflare workers comes with a really easy to setup CLI called [wrangler](https://github.com/cloudflare/wrangler) for wasm compilation and managing your serverless functions.

I use `wrangler build` to compile to wasm.

`cargo build` runs fine, but `wrangler build` has issues.  I have a basic [Cloudflare worker-rs](https://github.com/cloudflare/workers-rs) server setup using the default template. 

See below for full error report.

### What are you trying to accomplish?

I want to create a connection pool for my postgres db, using r2d2.

### Are you seeing any additional errors?

```
author@MacBook-Air server % wrangler build
🌀  Running cargo install -q worker-build && worker-build --release
[INFO]: 🎯  Checking for the Wasm target...
[INFO]: 🌀  Compiling to Wasm...
   Compiling scheduled-thread-pool v0.2.5
error[E0308]: mismatched types
   --> /Users/author/.cargo/registry/src/github.com-1ecc6299db9ec823/scheduled-thread-pool-0.2.5/src/lib.rs:342:61
    |
342 |                     self.shared.cvar.wait_until(&mut inner, now + t);
    |                                                             ^^^^^^^ expected struct `instant::wasm::Instant`, found struct `Instant`

For more information about this error, try `rustc --explain E0308`.
error: could not compile `scheduled-thread-pool` due to previous error
```

### Steps to reproduce

1. `cargo install wrangler`
2. `wrangler generate --type=rust project_name`
3. Add `diesel = { version = "1.4.4", features = ["postgres", "r2d2"] }` to `cargo.toml`
4. run `wrangler build` (if you take out r2d2, you will see that it builds fine without the r2d2 feature)

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [ ] This issue can be reproduced without requiring a third party crate
