### ISSUE TITLE
`schema.rs` doesn't compile when using "crate" as a table name

### ISSUE THREAD

**Issue by fwcd** [diesel-rs/diesel#3133]
### Versions

- **Rust:** 1.57.0
- **Diesel:** 1.4.8
- **Database:** Postgres
- **Operating System** macOS 12.3.1

### Feature Flags

- **diesel:** postgres

### What are you trying to accomplish?
Generate a working `schema.rs` using `diesel migration run`.

### What is the expected output?
A valid `schema.rs`.

### What is the actual output?
An invalid `schema.rs`, presumably because `crate` is a reserved keyword in Rust:

```
cannot find type `table` in the crate root
not found in the crate rootrustc[E0412](https://doc.rust-lang.org/error-index.html#E0412)
```

### Are you seeing any additional errors?
See above.

### Steps to reproduce

Create a small project of the following form:

`Cargo.toml`

```toml
[package]
name = "diesel-playground"
version = "0.1.0"
edition = "2021"

[dependencies]
diesel = { version = "1.4", features = ["postgres"] }
```

`src/main.rs`

```rust
#[macro_use]
extern crate diesel;

mod schema;

fn main() {}
```

`migrations/YYYY-MM-DD-00000_crate/up.sql`

```sql
CREATE TABLE crate (
  id SERIAL PRIMARY KEY
);
```

`migrations/YYYY-MM-DD-00000_crate/down.sql`

```sql
DROP TABLE crate;
```

Running `diesel migration run` should now generate the following files:

`diesel.toml`

```toml
# For documentation on how to configure this file,
# see diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
```

`src/schema.rs`

```rust
table! {
    crate (id) {
        id -> Int4,
    }
}
```

The schema, however, doesn't compile:

```
error: expected identifier, found keyword `crate`
 --> src/schema.rs:1:1
  |
1 | / table! {
2 | |     crate (id) {
3 | |         id -> Int4,
4 | |     }
5 | | }
  | |_^ expected identifier, found keyword
  |
  = note: this error originates in the macro `__diesel_table_impl` (in Nightly builds, run with -Z macro-backtrace for more info)

error: crate root imports need to be explicitly named: `use crate as name;`
 --> src/schema.rs:2:5
  |
2 |     crate (id) {
  |     ^^^^^

error: could not compile `diesel-playground` due to 3 previous errors
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
  - Possibly related to
    - #2809
    - #1897
    - #2090 
    - (those seem to deal with column names rather than table names though)
  - I suspect this is an unusual edge case, since the examples seem to encourage pluralized column names
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate
