### ISSUE TITLE
Compiling `diesel` for `arm64` on Ubuntu `x86`

### ISSUE THREAD

**Issue by AlbertMarashi** [diesel-rs/diesel#3476]
### Versions

- **Rust:** nightly-latest
- **Diesel:** `diesel = { version = "2.0.2", features = ["postgres", "r2d2"] }`
- **Database:** `postgres`
- **Operating System**: ubuntu-latest github actions x86

## Problem Description
I am trying to compile a rust serverless function using `cargo lambda`. The problem is that the github actions architecture is x86 and I am trying to compile an `arm64` binary.

I have done `sudo apt-get install libpq-dev` but I get issues towards the end of compilation.

This only happens with diesel in my project, as it requires external packages that need to be linked.

I'm hoping someone has faced this issue and might be able to help

### What is the actual output?
```
          /usr/bin/ld: /home/runner/work/graph-api/graph-api/target/aarch64-unknown-linux-gnu/release/deps/graph_server-37e3847e2f927b76.graph_server.e06d602e-cgu.0.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/runner/work/graph-api/graph-api/target/aarch64-unknown-linux-gnu/release/deps/graph_server-37e3847e2f927b76.graph_server.e06d602e-cgu.0.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/runner/work/graph-api/graph-api/target/aarch64-unknown-linux-gnu/release/deps/graph_server-37e3847e2f927b76.graph_server.e06d602e-cgu.0.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/runner/work/graph-api/graph-api/target/aarch64-unknown-linux-gnu/release/deps/graph_server-37e3847e2f927b76.graph_server.e06d602e-cgu.0.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/runner/work/graph-api/graph-api/target/aarch64-unknown-linux-gnu/release/deps/graph_server-37e3847e2f927b76.graph_server.e06d602e-cgu.0.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/runner/work/graph-api/graph-api/target/aarch64-unknown-linux-gnu/release/deps/graph_server-37e3847e2f927b76.graph_server.e06d602e-cgu.0.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/runner/work/graph-api/graph-api/target/aarch64-unknown-linux-gnu/release/deps/graph_server-37e3847e2f927b76.graph_server.e06d602e-cgu.0.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/runner/work/graph-api/graph-api/target/aarch64-unknown-linux-gnu/release/deps/graph_server-37e3847e2f927b76.graph_server.e06d602e-cgu.0.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/runner/work/graph-api/graph-api/target/aarch64-unknown-linux-gnu/release/deps/graph_server-37e3847e2f927b76.graph_server.e06d602e-cgu.0.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/runner/work/graph-api/graph-api/target/aarch64-unknown-linux-gnu/release/deps/graph_server-37e3847e2f927b76.graph_server.e06d602e-cgu.0.rcgu.o: error adding symbols: file in wrong format
          collect2: error: ld returned 1 exit status
          

warning: `graph-server` (bin "graph-server") generated 3 warnings
error: could not compile `graph-server` due to previous error; 3 warnings emitted
Error: Process completed with exit code 101.
```

### Steps to reproduce

**Github Action**
```yaml
name: deploy_api
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use arm architecture
        run: |
          sudo dpkg --add-architecture arm64
          sudo apt-get update
          sudo apt-get install libpq-dev libpq-dev:arm64
        continue-on-error: true
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      - name: Rustup target
        run: rustup target add aarch64-unknown-linux-gnu
      - name: Build
        run: cargo build --release --target aarch64-unknown-linux-gnu
 ```
