### ISSUE TITLE
Re-export the `sqlite3-bundled` feature of libsqlite3-sys

### ISSUE THREAD

**Issue by udoprog** [diesel-rs/diesel#3587]
This elaborates on the discussion in https://github.com/diesel-rs/diesel/discussions/3255

Without bundling, sqlite3 fails to link at least on Windows if there's no `sqlite3.lib` static lib available (which there usually isn't by default):

```
= note: LINK : fatal error LNK1181: cannot open input file 'sqlite3.lib'
```

These are my dependencies:

```toml
libsqlite3-sys = { version = "0.25.2", features = ["bundled", "unlock_notify"] }
diesel = { version = "2.0.3", features = ["sqlite", "chrono"] }
diesel_migrations = "2.0.0"
```

I explicitly add `libsqlite3-sys` because I need the `bundled` feature, but this leads to complicated version requirements in my project. This has frequently lead to a local `cargo upgrade` causing the build to break. In this instance, `cargo upgrade` bumped `libsqlite3-sys` to `0.26.0`:

```
    Updating crates.io index
error: failed to select a version for `libsqlite3-sys`.
    ... required by package `diesel v2.0.3`
    ... which satisfies dependency `diesel = "~2.0.0"` of package `diesel_migrations v2.0.0`
    ... which satisfies dependency `diesel_migrations = "^2.0.0"` of package `oxidize v0.0.0 (D:\Repo\projects\repos\OxidizeBot\bot)`
versions that meet the requirements `>=0.17.2, <0.26.0` are: 0.25.2, 0.25.1, 0.25.0, 0.24.2, 0.24.1, 0.24.0, 0.23.2, 0.23.1, 0.23.0, 0.22.2, 0.22.1, 0.22.0, 0.20.1, 0.20.0, 0.18.0, 0.17.3, 0.17.2

the package `libsqlite3-sys` links to the native library `sqlite3`, but it conflicts with a previous package which links to `sqlite3` as well:
package `libsqlite3-sys v0.26.0`
    ... which satisfies dependency `libsqlite3-sys = "^0.26.0"` of package `oxidize v0.0.0 (D:\Repo\projects\repos\OxidizeBot\bot)`
Only one package in the dependency graph may specify the same links value. This helps ensure that only one copy of a native library is linked in the final binary. Try to adjust your dependencies so that only one package uses the links ='libsqlite3-sys' value. For more information, see https://doc.rust-lang.org/cargo/reference/resolver.html#links.

failed to select a version for `libsqlite3-sys` which could resolve this conflict
```

By using a re-exported `sqlite3-bundled` feature instead, a local `cargo upgrade` wouldn't update the `libsqlite3-sys` version until `diesel` specifically is ready for it:

```toml
# don't really care what the feature is called :)
diesel = { version = "2.0.3", features = ["sqlite", "chrono", "sqlite3-bundled"] }
diesel_migrations = "2.0.0"
```

### Versions

- **Rust: rustc 1.68.2 (9eb3afe9e 2023-03-27)**
- **Diesel: 2.0.3**
- **Database: sqlite3**
- **Operating System: Windows**

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues)  and the [disussion forum](https://github.com/diesel-rs/diesel/discussions)  for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate
