### ISSUE TITLE
`diesel database reset` errors with `Failed to execute a database query`

### ISSUE THREAD

**Issue by musjj** [diesel-rs/diesel#4275]
### Versions

- **Rust:** `rustc 1.83.0-nightly (506f22b46 2024-09-19)`
- **Diesel:** `2.2.4`
- **Database:** `postgres`
- **Operating System:** Linux

### Feature Flags

- **diesel:** `["postgres"]`

### What are you trying to accomplish?

Run `diesel database reset`.

### What is the expected output?

Database is successfully reset.

### What is the actual output?

```
Dropping database: postgres
Failed to execute a database query: cannot drop the currently open database
```

### Are you seeing any additional errors?

No.

### Steps to reproduce

`.env`
```bash
DATABASE_URL="postgresql://postgres:postgres@localhost:5432/postgres"
```

`diesel.toml`
```toml
[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "migrations"
```

I only have one migration file:

`up.sql`
```sql
CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
);
```
`down.sql`
```sql
DROP TABLE IF EXISTS users;
```

## Checklist

- [x] I have already looked over the [issue tracker](https://github.com/diesel-rs/diesel/issues) and the [discussion forum](https://github.com/diesel-rs/diesel/discussions) for similar possible closed issues.
 
- [x] This issue can be reproduced on Rust's stable channel. (Your issue will be
  closed if this is not the case)
- [x] This issue can be reproduced without requiring a third party crate
