### ISSUE TITLE
Add a common rustfmt.toml for all diesel crates

### ISSUE THREAD

**Issue by weiznich** [diesel-rs/diesel#693]
Formatting a new patch set is quite hard, so this should be automated. We could try to use rustfmt for this. This would require writing a own rustfmt.toml to get some kind of common style similar to the current one. I'm not sure if it's possible to match the current style using rustfmt.

**Comment by killercup** [comment]
We tried that last year in #197. Does rustfmt support a diff-friendly formatting yet? All my cries for trailing commas and consistent block ident are to reduce git churn and rightward drift, basically.

**Comment by weiznich** [comment]
I played little bit with some rustfmt flags. The result is something like the following:

```rust
struct A {
    a: i32,
    b: i32,
}

trait Foo {}

trait Bar {}

trait Baz {}

fn foo<T, S, W, SomethingLonger>() -> ()
    where T: Foo,
        B: Baz,
        W: Foo,
        SomethingLonger: Foo + Baz + Bar,
{
    println!("")
}

fn boom<T>() -> ()
    where T: Foo,
{
    println!("")
}

fn many_args<T, B>(
    a: i32,
    b: i32,
    c: i32,
    d: i32,
    e: i32,
    f: i32,
    g: i32,
    h: i32,
    i: i32,
    j: i32,
    k: i32,
    l: i32,
    j: i32
) -> i32
    where T: Foo,
        B: Bar
{
    println!("")
}
```

Notability to the current format:

- where is moved to the line of the first where bound. I don't think this is a problem because adding a new bound will only add a new line
- function argument list does not have a tailing comma. This is unfortunate, but there seems no option to change this


The following rustfmt.toml was used

```toml
where_trailing_comma=true
where_pred_indent="Tabbed"

fn_return_indent="WithWhereClause"
fn_arg_indent="Tabbed"
fn_args_layout="Block"

struct_trailing_comma="Always"
struct_lit_trailing_comma="Always"

match_block_trailing_comma=true
match_wildcard_trailing_comma=true
```
